image: "ruby:latest"

stages:
  - test

rspec:
  stage: test
  script:
    - bundle install
    - bundle exec rspec
  artifacts:
    when: on_failure
    paths:
      - coverage

rails6_rspec:
  stage: test
  script:
    - ANY_OF_RAILS_6=true bundle install
    - ANY_OF_RAILS_6=true bundle exec rspec
  artifacts:
    when: on_failure
    paths:
      - coverage

rubocop:
  stage: test
  script:
    - bundle install
    - bundle exec rubocop
